<?php

namespace Database\Seeders;

use App\Models\PpdbRegistration;
use Illuminate\Database\Seeder;

class PpdbRegistrationSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        // Bersihkan data lama jika ingin reseed bersih
        PpdbRegistration::truncate();

        $students = [
            [
                'nomor_registrasi' => 'PPDB-2027-10492',
                'nama_lengkap' => 'Muhammad Rizky Pratama',
                'nama_panggilan' => 'Rizky',
                'nisn' => '0081298471',
                'nomor_kk' => '3201011203090001',
                'tempat_lahir' => 'Bogor',
                'tanggal_lahir_hari' => '14',
                'tanggal_lahir_bulan' => '5',
                'tanggal_lahir_tahun' => '2010',
                'jenis_kelamin' => 'L',
                'alamat_lengkap' => 'Jl. Raya Jakarta-Bogor Km. 43, Cibinong, Bogor',
                'sekolah_pilihan_level' => 'SMK',
                'sekolah_pilihan_unit' => 'SMK Plus Pelita Nusantara Bogor',
                'tipe_pendaftar' => 'Pendaftar Baru',
                'kelas_pilihan' => 'Kelas 10',
                'jurusan' => 'Pengembangan Perangkat Lunak dan Gim (PPLG)',
                'jalur_seleksi' => 'Reguler',
                'asal_sekolah' => 'SMP Negeri 1 Cibinong',
                'nomor_kontak_pendaftar' => '081298765432',
                'nomor_kontak_ortu' => '081312345678',
                'email' => 'rizky.pratama@gmail.com',
                'jenis_layanan' => ['Catering', 'Antar Jemput'],
                'sumber_info' => ['Brosur', 'Youtube'],
                'sumber_info_lainnya' => null,
                'alasan_minat' => 'Digitalisasi Sekolah',
                'alasan_minat_lainnya' => null,
                'ukuran_seragam' => 'L',
                'status' => 'terverifikasi',
                'catatan' => 'Berkas KK, Akta, dan Ijazah SMP telah lengkap dan terverifikasi.',
                'created_at' => now()->subDays(6),
            ],
            [
                'nomor_registrasi' => 'PPDB-2027-23819',
                'nama_lengkap' => 'Aisyah Putri Nurhaliza',
                'nama_panggilan' => 'Aisyah',
                'nisn' => '0089421892',
                'nomor_kk' => '3201012508100003',
                'tempat_lahir' => 'Depok',
                'tanggal_lahir_hari' => '22',
                'tanggal_lahir_bulan' => '8',
                'tanggal_lahir_tahun' => '2010',
                'jenis_kelamin' => 'P',
                'alamat_lengkap' => 'Perumahan Sukahati Indah Blok B3 No. 12, Cibinong',
                'sekolah_pilihan_level' => 'SMK',
                'sekolah_pilihan_unit' => 'SMK Plus Pelita Nusantara Bogor',
                'tipe_pendaftar' => 'Pendaftar Baru',
                'kelas_pilihan' => 'Kelas 10',
                'jurusan' => 'Desain Komunikasi Visual (DKV)',
                'jalur_seleksi' => 'Prestasi Akademik',
                'asal_sekolah' => 'SMP Negeri 2 Cibinong',
                'nomor_kontak_pendaftar' => '085712345678',
                'nomor_kontak_ortu' => '085887654321',
                'email' => 'aisyah.putri@gmail.com',
                'jenis_layanan' => ['Laundry'],
                'sumber_info' => ['Keluarga / Kerabat / Teman', 'Spanduk'],
                'sumber_info_lainnya' => null,
                'alasan_minat' => 'Gedung dan Sarana Lengkap',
                'alasan_minat_lainnya' => null,
                'ukuran_seragam' => 'M',
                'status' => 'lulus_seleksi',
                'catatan' => 'Lulus jalur prestasi peringkat 1 paralel. Siap pembayaran registrasi ulang.',
                'created_at' => now()->subDays(5),
            ],
            [
                'nomor_registrasi' => 'PPDB-2027-31045',
                'nama_lengkap' => 'Fajar Alamsyah',
                'nama_panggilan' => 'Fajar',
                'nisn' => '0081034928',
                'nomor_kk' => '3201010304090002',
                'tempat_lahir' => 'Bogor',
                'tanggal_lahir_hari' => '05',
                'tanggal_lahir_bulan' => '11',
                'tanggal_lahir_tahun' => '2009',
                'jenis_kelamin' => 'L',
                'alamat_lengkap' => 'Kp. Cipayung RT 02/05 Kel. Tengah, Cibinong',
                'sekolah_pilihan_level' => 'SMK',
                'sekolah_pilihan_unit' => 'SMK Plus Pelita Nusantara Bogor',
                'tipe_pendaftar' => 'Pendaftar Baru',
                'kelas_pilihan' => 'Kelas 10',
                'jurusan' => 'Teknik Jaringan Komputer dan Telekomunikasi (TJKT)',
                'jalur_seleksi' => 'Reguler',
                'asal_sekolah' => 'MTs Negeri 1 Bogor',
                'nomor_kontak_pendaftar' => '089612345678',
                'nomor_kontak_ortu' => '089687654321',
                'email' => 'fajar.alam@yahoo.com',
                'jenis_layanan' => ['Catering'],
                'sumber_info' => ['Pernah Datang Ke Sekolah'],
                'sumber_info_lainnya' => null,
                'alasan_minat' => 'Reputasi Sekolah Baik',
                'alasan_minat_lainnya' => null,
                'ukuran_seragam' => 'XL',
                'status' => 'menunggu_verifikasi',
                'catatan' => 'Menunggu bukti upload fotokopi raport semester 5.',
                'created_at' => now()->subDays(4),
            ],
            [
                'nomor_registrasi' => 'PPDB-2027-44920',
                'nama_lengkap' => 'Nabila Syakira Azzahra',
                'nama_panggilan' => 'Nabila',
                'nisn' => '0091823901',
                'nomor_kk' => '3201011802100004',
                'tempat_lahir' => 'Jakarta',
                'tanggal_lahir_hari' => '18',
                'tanggal_lahir_bulan' => '2',
                'tanggal_lahir_tahun' => '2010',
                'jenis_kelamin' => 'P',
                'alamat_lengkap' => 'Jl. Tegar Beriman No. 88, Pakansari, Cibinong',
                'sekolah_pilihan_level' => 'SMK',
                'sekolah_pilihan_unit' => 'SMK Plus Pelita Nusantara Bogor',
                'tipe_pendaftar' => 'Pendaftar Baru',
                'kelas_pilihan' => 'Kelas 10',
                'jurusan' => 'Broadcasting dan Perfilman (BC)',
                'jalur_seleksi' => 'Prestasi Non-Akademik',
                'asal_sekolah' => 'SMP IT Al Madinah',
                'nomor_kontak_pendaftar' => '082155667788',
                'nomor_kontak_ortu' => '082199887766',
                'email' => 'nabila.syakira@outlook.com',
                'jenis_layanan' => ['AHA Music Course'],
                'sumber_info' => ['Iklan', 'Youtube'],
                'sumber_info_lainnya' => null,
                'alasan_minat' => 'Kualitas Guru yang Baik',
                'alasan_minat_lainnya' => null,
                'ukuran_seragam' => 'S',
                'status' => 'terverifikasi',
                'catatan' => 'Juara 2 Lomba Video Pendek tingkat Provinsi.',
                'created_at' => now()->subDays(3),
            ],
            [
                'nomor_registrasi' => 'PPDB-2027-58213',
                'nama_lengkap' => 'Dimas Arya Pamungkas',
                'nama_panggilan' => 'Dimas',
                'nisn' => '0089201948',
                'nomor_kk' => '3201010909090005',
                'tempat_lahir' => 'Bogor',
                'tanggal_lahir_hari' => '09',
                'tanggal_lahir_bulan' => '9',
                'tanggal_lahir_tahun' => '2009',
                'jenis_kelamin' => 'L',
                'alamat_lengkap' => 'Jl. Karadenan No. 15, Cibinong, Bogor',
                'sekolah_pilihan_level' => 'SMK',
                'sekolah_pilihan_unit' => 'SMK Plus Pelita Nusantara Bogor',
                'tipe_pendaftar' => 'Pendaftar Baru',
                'kelas_pilihan' => 'Kelas 10',
                'jurusan' => 'Animasi',
                'jalur_seleksi' => 'Reguler',
                'asal_sekolah' => 'SMP Plus PGRI Cibinong',
                'nomor_kontak_pendaftar' => '087812344321',
                'nomor_kontak_ortu' => '087898766789',
                'email' => 'dimas.arya@gmail.com',
                'jenis_layanan' => ['Catering'],
                'sumber_info' => ['Brosur'],
                'sumber_info_lainnya' => null,
                'alasan_minat' => 'Gedung dan Sarana Lengkap',
                'alasan_minat_lainnya' => null,
                'ukuran_seragam' => 'M',
                'status' => 'menunggu_verifikasi',
                'catatan' => 'Menunggu verifikasi nilai wawancara peminatan.',
                'created_at' => now()->subDays(2),
            ],
            [
                'nomor_registrasi' => 'PPDB-2027-67104',
                'nama_lengkap' => 'Siti Maulida Rahmah',
                'nama_panggilan' => 'Maulida',
                'nisn' => '0092837461',
                'nomor_kk' => '3201013011100006',
                'tempat_lahir' => 'Bogor',
                'tanggal_lahir_hari' => '30',
                'tanggal_lahir_bulan' => '11',
                'tanggal_lahir_tahun' => '2010',
                'jenis_kelamin' => 'P',
                'alamat_lengkap' => 'Jl. Sirojul Munir No. 4, Jatisampurna, Cibinong',
                'sekolah_pilihan_level' => 'SMK',
                'sekolah_pilihan_unit' => 'SMK Plus Pelita Nusantara Bogor',
                'tipe_pendaftar' => 'Pendaftar Baru',
                'kelas_pilihan' => 'Kelas 10',
                'jurusan' => 'Akuntansi dan Keuangan Lembaga (AKL)',
                'jalur_seleksi' => 'Afirmasi / KETM',
                'asal_sekolah' => 'SMP Negeri 3 Cibinong',
                'nomor_kontak_pendaftar' => '083811223344',
                'nomor_kontak_ortu' => '083899887766',
                'email' => 'maulida.siti@gmail.com',
                'jenis_layanan' => ['Antar Jemput'],
                'sumber_info' => ['Keluarga / Kerabat / Teman'],
                'sumber_info_lainnya' => null,
                'alasan_minat' => 'Pelayanannya Ramah',
                'alasan_minat_lainnya' => null,
                'ukuran_seragam' => 'M',
                'status' => 'terverifikasi',
                'catatan' => 'Berkas KIP dan KKS valid.',
                'created_at' => now()->subDays(2),
            ],
            [
                'nomor_registrasi' => 'PPDB-2027-72911',
                'nama_lengkap' => 'Kevin Christian Tanuwidjaja',
                'nama_panggilan' => 'Kevin',
                'nisn' => '0087192834',
                'nomor_kk' => '3201011406090007',
                'tempat_lahir' => 'Jakarta Barat',
                'tanggal_lahir_hari' => '14',
                'tanggal_lahir_bulan' => '6',
                'tanggal_lahir_tahun' => '2009',
                'jenis_kelamin' => 'L',
                'alamat_lengkap' => 'Komplek Sentul City Cluster Taman Venesia No. 28, Babakan Madang',
                'sekolah_pilihan_level' => 'SMK',
                'sekolah_pilihan_unit' => 'SMK Plus Pelita Nusantara Bogor',
                'tipe_pendaftar' => 'Pendaftar Baru',
                'kelas_pilihan' => 'Kelas 10',
                'jurusan' => 'Pengembangan Perangkat Lunak dan Gim (PPLG)',
                'jalur_seleksi' => 'Prestasi Akademik',
                'asal_sekolah' => 'SMP Taruna Bangsa Sentul',
                'nomor_kontak_pendaftar' => '08119028371',
                'nomor_kontak_ortu' => '08112837491',
                'email' => 'kevin.tanu@gmail.com',
                'jenis_layanan' => ['Catering'],
                'sumber_info' => ['Website', 'Instagram'],
                'sumber_info_lainnya' => null,
                'alasan_minat' => 'Digitalisasi Sekolah',
                'alasan_minat_lainnya' => 'Minat game development Unreal Engine',
                'ukuran_seragam' => 'L',
                'status' => 'lulus_seleksi',
                'catatan' => 'Lulus seleksi wawancara teknis dan portfolio programming.',
                'created_at' => now()->subDay(),
            ],
            [
                'nomor_registrasi' => 'PPDB-2027-81402',
                'nama_lengkap' => 'Zahra Anindya Safitri',
                'nama_panggilan' => 'Zahra',
                'nisn' => '0093847192',
                'nomor_kk' => '3201012903100008',
                'tempat_lahir' => 'Bogor',
                'tanggal_lahir_hari' => '29',
                'tanggal_lahir_bulan' => '3',
                'tanggal_lahir_tahun' => '2010',
                'jenis_kelamin' => 'P',
                'alamat_lengkap' => 'Jl. Mayor Oking Jaya Atmaja No. 51, Citeureup, Bogor',
                'sekolah_pilihan_level' => 'SMK',
                'sekolah_pilihan_unit' => 'SMK Plus Pelita Nusantara Bogor',
                'tipe_pendaftar' => 'Pendaftar Baru',
                'kelas_pilihan' => 'Kelas 10',
                'jurusan' => 'Manajemen Perkantoran dan Layanan Bisnis (MPLB)',
                'jalur_seleksi' => 'Reguler',
                'asal_sekolah' => 'SMP Negeri 1 Citeureup',
                'nomor_kontak_pendaftar' => '085210928374',
                'nomor_kontak_ortu' => '085293847192',
                'email' => 'zahra.anindya@gmail.com',
                'jenis_layanan' => ['Antar Jemput'],
                'sumber_info' => ['Brosur', 'Keluarga / Kerabat / Teman'],
                'sumber_info_lainnya' => null,
                'alasan_minat' => 'Reputasi Sekolah Baik',
                'alasan_minat_lainnya' => null,
                'ukuran_seragam' => 'S',
                'status' => 'menunggu_verifikasi',
                'catatan' => 'Menunggu verifikasi fisik akta kelahiran.',
                'created_at' => now()->subHours(18),
            ],
            [
                'nomor_registrasi' => 'PPDB-2027-90384',
                'nama_lengkap' => 'Bagas Dwi Wicaksono',
                'nama_panggilan' => 'Bagas',
                'nisn' => '0082938475',
                'nomor_kk' => '3201011005090009',
                'tempat_lahir' => 'Sukabumi',
                'tanggal_lahir_hari' => '10',
                'tanggal_lahir_bulan' => '5',
                'tanggal_lahir_tahun' => '2009',
                'jenis_kelamin' => 'L',
                'alamat_lengkap' => 'Jl. Kolonel Edy Yoso Martadipura No. 12, Pakansari',
                'sekolah_pilihan_level' => 'SMK',
                'sekolah_pilihan_unit' => 'SMK Plus Pelita Nusantara Bogor',
                'tipe_pendaftar' => 'Pendaftar Baru',
                'kelas_pilihan' => 'Kelas 10',
                'jurusan' => 'Teknik Jaringan Komputer dan Telekomunikasi (TJKT)',
                'jalur_seleksi' => 'Reguler',
                'asal_sekolah' => 'SMP PGRI 1 Cibinong',
                'nomor_kontak_pendaftar' => '087719283746',
                'nomor_kontak_ortu' => '087792837465',
                'email' => 'bagas.wicaksono@yahoo.com',
                'jenis_layanan' => ['Catering'],
                'sumber_info' => ['Spanduk'],
                'sumber_info_lainnya' => null,
                'alasan_minat' => 'Gedung dan Sarana Lengkap',
                'alasan_minat_lainnya' => null,
                'ukuran_seragam' => 'XL',
                'status' => 'terverifikasi',
                'catatan' => 'Berkas pendaftaran telah lengkap.',
                'created_at' => now()->subHours(12),
            ],
            [
                'nomor_registrasi' => 'PPDB-2027-94812',
                'nama_lengkap' => 'Rania Khalisa Marwa',
                'nama_panggilan' => 'Rania',
                'nisn' => '0094829103',
                'nomor_kk' => '3201011907100010',
                'tempat_lahir' => 'Bogor',
                'tanggal_lahir_hari' => '19',
                'tanggal_lahir_bulan' => '7',
                'tanggal_lahir_tahun' => '2010',
                'jenis_kelamin' => 'P',
                'alamat_lengkap' => 'Perum Griya Bukit Jaya Blok N5 No. 10, Gunung Putri',
                'sekolah_pilihan_level' => 'SMK',
                'sekolah_pilihan_unit' => 'SMK Plus Pelita Nusantara Bogor',
                'tipe_pendaftar' => 'Pendaftar Baru',
                'kelas_pilihan' => 'Kelas 10',
                'jurusan' => 'Desain Komunikasi Visual (DKV)',
                'jalur_seleksi' => 'Prestasi Non-Akademik',
                'asal_sekolah' => 'SMP Negeri 1 Gunung Putri',
                'nomor_kontak_pendaftar' => '081392817263',
                'nomor_kontak_ortu' => '081398271625',
                'email' => 'rania.khalisa@gmail.com',
                'jenis_layanan' => ['Antar Jemput'],
                'sumber_info' => ['Instagram', 'Youtube'],
                'sumber_info_lainnya' => null,
                'alasan_minat' => 'Kurikulum Merdeka Unggulan',
                'alasan_minat_lainnya' => null,
                'ukuran_seragam' => 'M',
                'status' => 'lulus_seleksi',
                'catatan' => 'Lulus seleksi portfolio desain ilustrasi.',
                'created_at' => now()->subHours(8),
            ],
            [
                'nomor_registrasi' => 'PPDB-2027-98124',
                'nama_lengkap' => 'Farrel Raditya Pratama',
                'nama_panggilan' => 'Farrel',
                'nisn' => '0083928174',
                'nomor_kk' => '3201010812090011',
                'tempat_lahir' => 'Bogor',
                'tanggal_lahir_hari' => '08',
                'tanggal_lahir_bulan' => '12',
                'tanggal_lahir_tahun' => '2009',
                'jenis_kelamin' => 'L',
                'alamat_lengkap' => 'Jl. KSR Dadi Kusmayadi No. 22, Sukahati, Cibinong',
                'sekolah_pilihan_level' => 'SMK',
                'sekolah_pilihan_unit' => 'SMK Plus Pelita Nusantara Bogor',
                'tipe_pendaftar' => 'Pendaftar Baru',
                'kelas_pilihan' => 'Kelas 10',
                'jurusan' => 'Animasi',
                'jalur_seleksi' => 'Reguler',
                'asal_sekolah' => 'SMP Negeri 4 Cibinong',
                'nomor_kontak_pendaftar' => '087891827364',
                'nomor_kontak_ortu' => '087819283746',
                'email' => 'farrel.raditya@gmail.com',
                'jenis_layanan' => ['Catering'],
                'sumber_info' => ['Brosur'],
                'sumber_info_lainnya' => null,
                'alasan_minat' => 'Fasilitas Lab Komputer 3D',
                'alasan_minat_lainnya' => null,
                'ukuran_seragam' => 'L',
                'status' => 'menunggu_verifikasi',
                'catatan' => 'Perlu pengecekan pasfoto terbaru.',
                'created_at' => now()->subHours(4),
            ],
            [
                'nomor_registrasi' => 'PPDB-2027-99231',
                'nama_lengkap' => 'Clarissa Aurelia Putri',
                'nama_panggilan' => 'Clarissa',
                'nisn' => '0092817263',
                'nomor_kk' => '3201012104100012',
                'tempat_lahir' => 'Tangerang',
                'tanggal_lahir_hari' => '21',
                'tanggal_lahir_bulan' => '4',
                'tanggal_lahir_tahun' => '2010',
                'jenis_kelamin' => 'P',
                'alamat_lengkap' => 'Cluster Bellanova No. A8, Sentul City, Babakan Madang',
                'sekolah_pilihan_level' => 'SMK',
                'sekolah_pilihan_unit' => 'SMK Plus Pelita Nusantara Bogor',
                'tipe_pendaftar' => 'Pendaftar Baru',
                'kelas_pilihan' => 'Kelas 10',
                'jurusan' => 'Manajemen Perkantoran dan Layanan Bisnis (MPLB)',
                'jalur_seleksi' => 'Prestasi Akademik',
                'asal_sekolah' => 'SMP Pelita Harapan Sentul',
                'nomor_kontak_pendaftar' => '081283749102',
                'nomor_kontak_ortu' => '081293847192',
                'email' => 'clarissa.aurelia@gmail.com',
                'jenis_layanan' => ['Catering', 'Antar Jemput'],
                'sumber_info' => ['Instagram', 'Website'],
                'sumber_info_lainnya' => null,
                'alasan_minat' => 'Reputasi Sekolah Baik',
                'alasan_minat_lainnya' => null,
                'ukuran_seragam' => 'S',
                'status' => 'terverifikasi',
                'catatan' => 'Semua berkas sah dan terverifikasi.',
                'created_at' => now()->subMinutes(90),
            ],
            [
                'nomor_registrasi' => 'PPDB-2027-99540',
                'nama_lengkap' => 'Danendra Arya Bimasena',
                'nama_panggilan' => 'Danen',
                'nisn' => '0089102938',
                'nomor_kk' => '3201011501090013',
                'tempat_lahir' => 'Bogor',
                'tanggal_lahir_hari' => '15',
                'tanggal_lahir_bulan' => '1',
                'tanggal_lahir_tahun' => '2009',
                'jenis_kelamin' => 'L',
                'alamat_lengkap' => 'Jl. Raya Cikaret No. 45, Harapan Jaya, Cibinong',
                'sekolah_pilihan_level' => 'SMK',
                'sekolah_pilihan_unit' => 'SMK Plus Pelita Nusantara Bogor',
                'tipe_pendaftar' => 'Pendaftar Baru',
                'kelas_pilihan' => 'Kelas 10',
                'jurusan' => 'Broadcasting dan Perfilman (BC)',
                'jalur_seleksi' => 'Reguler',
                'asal_sekolah' => 'SMP Negeri 1 Bojonggede',
                'nomor_kontak_pendaftar' => '085691827364',
                'nomor_kontak_ortu' => '085619283746',
                'email' => 'danendra.arya@gmail.com',
                'jenis_layanan' => ['Catering'],
                'sumber_info' => ['Youtube', 'Brosur'],
                'sumber_info_lainnya' => null,
                'alasan_minat' => 'Studio Siaran Televisi Lengkap',
                'alasan_minat_lainnya' => null,
                'ukuran_seragam' => 'XL',
                'status' => 'menunggu_verifikasi',
                'catatan' => 'Pendaftaran online baru masuk hari ini.',
                'created_at' => now()->subMinutes(45),
            ],
            [
                'nomor_registrasi' => 'PPDB-2027-99881',
                'nama_lengkap' => 'Tiara Maharani Kusuma',
                'nama_panggilan' => 'Tiara',
                'nisn' => '0091827394',
                'nomor_kk' => '3201011111100014',
                'tempat_lahir' => 'Bandung',
                'tanggal_lahir_hari' => '11',
                'tanggal_lahir_bulan' => '11',
                'tanggal_lahir_tahun' => '2010',
                'jenis_kelamin' => 'P',
                'alamat_lengkap' => 'Jl. Alternatif Sentul No. 101, Cijujung, Sukaraja',
                'sekolah_pilihan_level' => 'SMK',
                'sekolah_pilihan_unit' => 'SMK Plus Pelita Nusantara Bogor',
                'tipe_pendaftar' => 'Pendaftar Baru',
                'kelas_pilihan' => 'Kelas 10',
                'jurusan' => 'Akuntansi dan Keuangan Lembaga (AKL)',
                'jalur_seleksi' => 'Prestasi Akademik',
                'asal_sekolah' => 'SMP Negeri 1 Sukaraja',
                'nomor_kontak_pendaftar' => '081382910293',
                'nomor_kontak_ortu' => '081392819283',
                'email' => 'tiara.maharani@gmail.com',
                'jenis_layanan' => ['Laundry', 'Catering'],
                'sumber_info' => ['Keluarga / Kerabat / Teman'],
                'sumber_info_lainnya' => null,
                'alasan_minat' => 'Akreditasi A & Kerjasama Industri Bank',
                'alasan_minat_lainnya' => null,
                'ukuran_seragam' => 'M',
                'status' => 'lulus_seleksi',
                'catatan' => 'Lulus beasiswa prestasi nilai rapor 92.5.',
                'created_at' => now()->subMinutes(15),
            ],
        ];

        foreach ($students as $student) {
            PpdbRegistration::create($student);
        }
    }
}
